### ISSUE TITLE
getObject和putObject支持File

### ISSUE THREAD

**Issue by feimenggo** [meetleev/flutter_qcloud_cos_client#1]
可以getObject保存到File和putObject上传File吗？如果文件很大，使用Uint8List就会内存不够。

**Comment by meetleev** [comment]
以文件路径形参上传本质上还是要把文件读取到本地然后上传的

``` dart
  final file = File(filePath);
  final length = await file.length();
  final stream = file.openRead();
```

多个文件上传控制下并发量 

单个文件太大可以考虑分段上传/下载

**Comment by feimenggo** [comment]
以流的方式传参，就不会直接把整个文件加载到内存吧？
现在有分段上传和下载的功能吗？比如：要上传/下载1G的文件，私有读写的存储桶还无法使用其他库。
