### ISSUE TITLE
xml解析失败

### ISSUE THREAD

**Issue by feimenggo** [meetleev/flutter_qcloud_cos_client#3]
响应xml数据解析后，message的字段都为null
<img width="984" alt="image" src="https://github.com/meetleev/flutter_qcloud_cos_client/assets/12608693/d8d7b568-5a08-4960-8b8b-edfee94c3a3b">

**Comment by meetleev** [comment]
access denied, code 403

**Comment by feimenggo** [comment]
这个问题修复了？当statusCode非200的时候，捕获CosServiceError异常的字段都是null啊。
